/**
 * nginx-apps.ts — Dynamic nginx config management for App Store containers
 *
 * Problem: Agent2077 is reached via http://agent2077.local because Avahi
 * advertises the machine hostname and nginx listens on port 80. But Docker
 * app containers bind to host ports 9001-9100, and nginx doesn't listen on
 * those ports — so http://agent2077.local:9001 returns a connection refused
 * even though http://192.168.x.x:9001 works fine.
 *
 * Solution: For each running app, write a small nginx server block to
 *   /etc/nginx/conf.d/agent2077-app-<port>.conf
 * that listens on that port and proxies to localhost:<port>, then reload
 * nginx. On stop/delete, remove the file and reload again.
 *
 * Ubuntu's main /etc/nginx/nginx.conf already includes /etc/nginx/conf.d/*.conf
 * inside its http{} block, so the per-app confs are picked up automatically.
 * The Agent2077 sites file (sites-enabled/agent2077) does NOT include them —
 * doing so would cause a double-registration conflict and show "Welcome to nginx".
 *
 * Permissions: Agent2077 runs as root or with sudo on most installs.
 * If the write fails (permission denied), we log a warning and continue —
 * the app still works via the direct IP, just not via .local.
 */

import { execSync } from "child_process";
import fs from "fs";
import path from "path";

// Store per-app nginx confs inside the Agent2077 install directory.
// This directory is owned by the Agent2077 process user so no sudo or
// special group permissions are needed to write conf files.
// nginx only needs READ access (www-data), which it already has for files
// in world-readable directories. The install script creates this dir and
// adds the include line to the nginx sites file pointing here.
const NGINX_CONF_DIR = path.join(process.cwd(), "nginx-apps");

/**
 * Generate the nginx server block for a single app port.
 * Listens on `port` for any hostname (so agent2077.local:<port> works)
 * and proxies to the Docker container on localhost:<port>.
 */
function buildAppConf(hostPort: number, containerPort: number): string {
  return `# Auto-generated by Agent2077 — do not edit manually.
# Removed automatically when the app is stopped or deleted.
#
# nginx listens on host port ${hostPort}.
# proxy_pass sends to 127.0.0.1:${hostPort} (the Docker host-side port).
# Docker's port mapping (via docker-proxy) receives that connection and
# forwards it to the container on port ${containerPort}.
# This is NOT a loop — docker-proxy owns 0.0.0.0:${hostPort}, not nginx.
server {
    listen ${hostPort};
    server_name _;

    location / {
        proxy_pass http://127.0.0.1:${hostPort};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Required for SSE / streaming apps
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
}
`;
}

function confPath(port: number): string {
  return path.join(NGINX_CONF_DIR, `agent2077-app-${port}.conf`);
}

/**
 * Reload nginx config. Uses `nginx -s reload` (graceful reload — zero downtime).
 * If nginx isn't running or the user doesn't have permission, logs and continues.
 */
function reloadNginx(): void {
  try {
    execSync("nginx -s reload", { stdio: "pipe" });
    console.log("[nginx-apps] nginx reloaded successfully");
  } catch (err: any) {
    // Try with sudo in case Agent2077 isn't running as root
    try {
      execSync("sudo nginx -s reload", { stdio: "pipe" });
      console.log("[nginx-apps] nginx reloaded (via sudo)");
    } catch (err2: any) {
      console.warn(
        "[nginx-apps] Could not reload nginx — apps will still work via IP but not via agent2077.local:<port>.",
        err2.message
      );
    }
  }
}

/**
 * Write a per-port nginx server block and reload nginx.
 * Called when an app starts (or is first deployed).
 */
export function registerAppPort(port: number): void {
  const dest = confPath(port);
  try {
    // Ensure the conf dir exists (owned by the Agent2077 process user)
    if (!fs.existsSync(NGINX_CONF_DIR)) {
      fs.mkdirSync(NGINX_CONF_DIR, { recursive: true });
      console.log(`[nginx-apps] Created nginx-apps dir: ${NGINX_CONF_DIR}`);
    }
    fs.writeFileSync(dest, buildAppConf(port), "utf-8");
    console.log(`[nginx-apps] Wrote ${dest}`);
    reloadNginx();
  } catch (err: any) {
    // Permission denied is the common case if not running as root
    console.warn(`[nginx-apps] Failed to write ${dest}: ${err.message}`);
    console.warn(`[nginx-apps] App will be accessible via direct IP but not via agent2077.local:${port}`);
    console.warn(`[nginx-apps] To fix permanently, run Agent2077 as root or add the agent2077 user to the nginx sudoers file.`);
  }
}

/**
 * Remove the per-port nginx server block and reload nginx.
 * Called when an app stops or is deleted.
 */
export function unregisterAppPort(port: number): void {
  const dest = confPath(port);
  try {
    if (fs.existsSync(dest)) {
      fs.unlinkSync(dest);
      console.log(`[nginx-apps] Removed ${dest}`);
      reloadNginx();
    }
  } catch (err: any) {
    console.warn(`[nginx-apps] Failed to remove ${dest}: ${err.message}`);
  }
}

/**
 * On startup, sync nginx configs for all currently-running apps.
 * This handles the case where Agent2077 restarts but Docker containers
 * are still running — their nginx configs may have been lost.
 */
export function syncNginxForRunningApps(runningApps: Array<{ port?: number | null }>): void {
  let changed = false;
  // Ensure conf dir exists
  if (!fs.existsSync(NGINX_CONF_DIR)) {
    try { fs.mkdirSync(NGINX_CONF_DIR, { recursive: true }); } catch { /* ignore */ }
  }
  for (const app of runningApps) {
    if (!app.port) continue;
    const dest = confPath(app.port);
    if (!fs.existsSync(dest)) {
      try {
        fs.writeFileSync(dest, buildAppConf(app.port), "utf-8");
        console.log(`[nginx-apps] Restored missing config for port ${app.port}`);
        changed = true;
      } catch (err: any) {
        console.warn(`[nginx-apps] Could not restore config for port ${app.port}: ${err.message}`);
      }
    }
  }
  if (changed) reloadNginx();
}
